apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: ai-cloud-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: ai-cloud-operator
  ports:
  - name: https
    port: 443
    targetPort: 9443
    protocol: TCP
