---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - ai-cloud-operator-gateway-key
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resourceNames:
  - ai-cloud-operator-token
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
