#!/usr/bin/env bash
# Regenerates charts/ai-cloud-operator from config/* via helmify, then
# reapplies the handful of customizations helmify has no flag for (and
# would otherwise overwrite on every run — see its README's "Known
# issues": it overwrites every template + values.yaml it generates, every
# time). config/* stays the single source of truth; this script is what
# keeps the chart in sync with it instead of that being a manual chore.
#
# What's safe to leave untouched across reruns: any template file helmify
# never generates in the first place (it only overwrites files it owns, and
# never deletes others) — that covers templates/ingress.yaml and
# templates/secret.yaml, since neither Ingress nor the out-of-band
# ENROLLMENT_SECRET Secret are part of `kustomize build config/default`'s
# output. What needs reapplying every run: values.yaml and
# templates/deployment.yaml, both regenerated from scratch every time.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

CHART_DIR=charts/ai-cloud-operator
OVERRIDES_DIR=hack/helm-overrides

KUSTOMIZE="${KUSTOMIZE:-bin/kustomize}"
HELMIFY="${HELMIFY:-bin/helmify}"
YQ="${YQ:-bin/yq}"

mkdir -p "$CHART_DIR"

# kustomize's configMapGenerator suffixes the params ConfigMap's name with a
# content hash (e.g. ai-cloud-operator-params-g6274tctct) so that editing
# params.env forces a new ConfigMap name, which is what actually triggers a
# pod rollout in a kustomize-managed cluster. In the chart, the equivalent
# job is done by the checksum/params annotation in the hand-maintained
# deployment.yaml override instead (see its comment) — so the hash suffix
# here only adds churn to the generated file/value names, stripped before
# helmify ever sees it.
"$KUSTOMIZE" build config/default \
  | sed -E 's/(ai-cloud-operator-params)-[a-z0-9]+/\1/g' \
  | "$HELMIFY" -optional-crds -generate-defaults "$CHART_DIR"

# helmify unconditionally adds a KUBERNETES_CLUSTER_DOMAIN env var/value as
# a convention for kubebuilder-scaffolded operators — this operator never
# reads it (see cmd/main.go's setupConvexIntegration), so it's dead config
# surface every values.yaml reader has to puzzle over. Dropped from
# values.yaml here; the deployment.yaml override below never carried the
# env var in the first place.
"$YQ" -i 'del(.kubernetesClusterDomain)' "$CHART_DIR/values.yaml"

# CRD schema changes should roll out via the normal ArgoCD sync like
# everything else in this chart (see the -optional-crds flag above, which
# already keeps it a regular template instead of Helm's non-upgradeable
# native crds/ directory) — but `helm.sh/resource-policy: keep` still
# stops `helm uninstall`/a pruning sync from deleting it and taking every
# Workload custom resource down with it. helmify has no flag for this
# annotation, so it's inserted after every regeneration.
if ! grep -q 'helm.sh/resource-policy: keep' "$CHART_DIR/templates/workload-crd.yaml"; then
  sed -i '0,/^  annotations:$/s//  annotations:\n    helm.sh\/resource-policy: keep/' "$CHART_DIR/templates/workload-crd.yaml"
fi

# Values helmify doesn't know to add: the real GHCR image (it defaults to
# the kustomize placeholder "controller:latest"), and this chart's own
# additions (enrollmentSecret's existing-Secret-or-inline-value toggle,
# ingress). Merged on top of whatever helmify just (re)generated.
"$YQ" -i '. *= load("'"$OVERRIDES_DIR"'/values-overlay.yaml")' "$CHART_DIR/values.yaml"

# templates/deployment.yaml is regenerated by helmify every run (Deployment
# is very much part of kustomize's output), so unlike ingress.yaml/
# secret.yaml it can't just be left alone — it's fully hand-maintained in
# the overrides dir and copied on top after every helmify run. Diff it
# against the freshly generated one after changing config/manager/
# manager.yaml, to catch upstream changes (new env vars, probes, etc.) this
# override needs to pick up too.
cp "$OVERRIDES_DIR/templates/deployment.yaml" "$CHART_DIR/templates/deployment.yaml"

echo "charts/ai-cloud-operator regenerated from config/*."
