apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-cloud-operator.fullname" . }}-api
  labels:
    control-plane: controller-manager
  {{- include "ai-cloud-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app.kubernetes.io/name: ai-cloud-operator
    control-plane: controller-manager
    {{- include "ai-cloud-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.api.ports | toYaml | nindent 2 }}
