apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ai-cloud-operator.fullname" . }}-manager-role
  labels:
  {{- include "ai-cloud-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods/exec
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - ai-cloud-operator-env
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - ai-cloud-operator-gateway-key
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resourceNames:
  - ai-cloud-operator-token
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - apps.aicloud.dev
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ai-cloud-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "ai-cloud-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "ai-cloud-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "ai-cloud-operator.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
