{{- if not .Values.enrollmentSecret.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-cloud-operator.fullname" . }}-enrollment-secret
  labels:
  {{- include "ai-cloud-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENROLLMENT_SECRET: {{ required "enrollmentSecret.value is required when enrollmentSecret.existingSecretName is not set" .Values.enrollmentSecret.value | quote }}
{{- end }}
